language: python
python:
#  - "2.6" not supported (at the moment, because unittest's "assertRegex")
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
install:
    pip install coveralls

script:
    coverage run --source=gitshelve setup.py test
after_success:
    coveralls
